projects:
  instagramclone:
    schemaPath: amplify/backend/api/instagramclone/build/schema.graphql
    includes:
      - 'y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /graphql
extensions:
  amplify:
    version: 3
